# -*- coding: utf-8 -*-
"""Tree growth analysis data sci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKajlG1LD4t3rWDgWEK5We79u1gGoL8x
"""

import pandas as pd
import matplotlib.pyplot as plt

tree_types = []
tree_heights = []
tree_ages = []

n = int(input("How many trees are going to enter their description? "))

for i in range(n):
    print(f"\nTree {i+1}")
    name = input("Enter tree type: ")
    height = float(input("Enter tree's height (m): "))
    age = float(input("Enter tree's age (years and . for months): "))

    tree_types.append(name)
    tree_heights.append(height)
    tree_ages.append(age)

df = pd.DataFrame({
    "Tree type": tree_types,
    "Tree height": tree_heights,
    "Tree age": tree_ages
})

print("\n=== Tree Growth Data ===")
print(df)

# Average height
print("\nAverage height:", df["Tree height"].mean())

# Tallest tree
tallest_tree = df.loc[df["Tree height"].idxmax()]
print("\nTallest tree:")
print(tallest_tree)

# Bar chart of tree heights
plt.figure()
plt.bar(tree_types, tree_heights)
plt.title("Tree Height Analysis")
plt.xlabel("Tree Type")
plt.ylabel("Height (m)")
plt.show()